In [1]:
import clickhouse_connect
import polars as pl

client = clickhouse_connect.get_client(host="localhost", port=8123, username="default", password="changeme")

In [10]:
result = client.query("SELECT * FROM fact_subscription_events where platform = 'fenster'")
pl.DataFrame(result.result_rows, schema=result.column_names, orient="row")

shape: (4_616, 17)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ event_id  ┆ customer_ ┆ platform ┆ event_tim ┆ … ┆ device_ty ┆ app_versi ┆ session_i ┆ internal_ │
│ ---       ┆ uuid      ┆ ---      ┆ estamp    ┆   ┆ pe        ┆ on        ┆ d         ┆ ref       │
│ str       ┆ ---       ┆ str      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆          ┆ datetime[ ┆   ┆ str       ┆ null      ┆ null      ┆ str       │
│           ┆           ┆          ┆ μs]       ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ FEN-00001 ┆ FEN_C0000 ┆ fenster  ┆ 2025-02-2 ┆ … ┆ windows   ┆ null      ┆ null      ┆ 45e930e5  │
│           ┆ 1         ┆          ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 07:06:24  ┆   ┆           ┆           ┆           ┆           │
│ FEN-00002 ┆ FEN_C0000 ┆ fenster  ┆ 2025-02-2 ┆ … ┆ android   ┆ null      ┆ null      ┆ 5603999b  │
│           ┆ 2         ┆          ┆ 1         ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 14:02:28  ┆   ┆           ┆           ┆           ┆           │
│ FEN-00003 ┆ FEN_C0000 ┆ fenster  ┆ 2025-02-1 ┆ … ┆ linux     ┆ null      ┆ null      ┆ b2df595b  │
│           ┆ 3         ┆          ┆ 1         ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 05:42:54  ┆   ┆           ┆           ┆           ┆           │
│ FEN-00004 ┆ FEN_C0000 ┆ fenster  ┆ 2025-02-2 ┆ … ┆ ios       ┆ null      ┆ null      ┆ 885b0070  │
│           ┆ 4         ┆          ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 00:46:38  ┆   ┆           ┆           ┆           ┆           │
│ FEN-00005 ┆ FEN_C0000 ┆ fenster  ┆ 2025-02-2 ┆ … ┆ windows   ┆ null      ┆ null      ┆ e28dcafe  │
│           ┆ 5         ┆          ┆ 6         ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 01:59:26  ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ FEN-01211 ┆ FEN_C0062 ┆ fenster  ┆ 2026-02-0 ┆ … ┆ android   ┆ null      ┆ null      ┆ 740066e6  │
│           ┆ 6         ┆          ┆ 9         ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 09:57:50  ┆   ┆           ┆           ┆           ┆           │
│ FEN-01213 ┆ FEN_C0062 ┆ fenster  ┆ 2026-02-1 ┆ … ┆ windows   ┆ null      ┆ null      ┆ 872f23b6  │
│           ┆ 7         ┆          ┆ 0         ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 03:40:01  ┆   ┆           ┆           ┆           ┆           │
│ FEN-01215 ┆ FEN_C0121 ┆ fenster  ┆ 2026-03-3 ┆ … ┆ windows   ┆ null      ┆ null      ┆ 5b628b30  │
│           ┆ 5         ┆          ┆ 1         ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 08:00:00  ┆   ┆           ┆           ┆           ┆           │
│ FEN-01216 ┆ FEN_C0121 ┆ fenster  ┆ 2026-02-1 ┆ … ┆ windows   ┆ null      ┆ null      ┆ 8bce7bcd  │
│           ┆ 6         ┆          ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 08:00:00  ┆   ┆           ┆           ┆           ┆           │
│ FEN-01217 ┆ FEN_C0121 ┆ fenster  ┆ 2026-03-0 ┆ … ┆ windows   ┆ null      ┆ null      ┆ 681c9d56  │
│           ┆ 7         ┆          ┆ 4         ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 08:00:00  ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [8]:
result = client.query("SELECT * FROM dim_customer where platform = 'apfel'")
pl.DataFrame(result.result_rows, schema=result.column_names, orient="row")

shape: (752, 10)
┌────────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ customer_u ┆ platform ┆ customer_ ┆ customer_ ┆ … ┆ city      ┆ postal_co ┆ language ┆ updated_a │
│ uid        ┆ ---      ┆ email     ┆ created_a ┆   ┆ ---       ┆ de        ┆ ---      ┆ t         │
│ ---        ┆ str      ┆ ---       ┆ t         ┆   ┆ str       ┆ ---       ┆ null     ┆ ---       │
│ str        ┆          ┆ str       ┆ ---       ┆   ┆           ┆ str       ┆          ┆ datetime[ │
│            ┆          ┆           ┆ datetime[ ┆   ┆           ┆           ┆          ┆ μs]       │
│            ┆          ┆           ┆ μs]       ┆   ┆           ┆           ┆          ┆           │
╞════════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ APF_C00001 ┆ apfel    ┆ user1@ema ┆ 2025-02-0 ┆ … ┆ Frankfurt ┆ 60311     ┆ null     ┆ 2026-10-1 │
│            ┆          ┆ il.com    ┆ 4         ┆   ┆           ┆           ┆          ┆ 3         │
│            ┆          ┆           ┆ 06:47:17  ┆   ┆           ┆           ┆          ┆ 00:30:55  │
│ APF_C00002 ┆ apfel    ┆ user2@ema ┆ 2025-02-1 ┆ … ┆ Hamburg   ┆ 20095     ┆ null     ┆ 2026-10-1 │
│            ┆          ┆ il.com    ┆ 9         ┆   ┆           ┆           ┆          ┆ 3         │
│            ┆          ┆           ┆ 14:51:55  ┆   ┆           ┆           ┆          ┆ 00:30:55  │
│ APF_C00003 ┆ apfel    ┆ user3@tes ┆ 2025-02-2 ┆ … ┆ Cardiff   ┆ CF10      ┆ null     ┆ 2026-10-1 │
│            ┆          ┆ t.com     ┆ 4         ┆   ┆           ┆           ┆          ┆ 3         │
│            ┆          ┆           ┆ 20:34:07  ┆   ┆           ┆           ┆          ┆ 00:30:55  │
│ APF_C00004 ┆ apfel    ┆ user4@ema ┆ 2025-02-1 ┆ … ┆ Cardiff   ┆ CF10      ┆ null     ┆ 2026-10-1 │
│            ┆          ┆ il.com    ┆ 5         ┆   ┆           ┆           ┆          ┆ 3         │
│            ┆          ┆           ┆ 17:10:23  ┆   ┆           ┆           ┆          ┆ 00:30:55  │
│ APF_C00005 ┆ apfel    ┆ user5@ema ┆ 2025-02-2 ┆ … ┆ Cardiff   ┆ CF10      ┆ null     ┆ 2026-10-1 │
│            ┆          ┆ il.com    ┆ 7         ┆   ┆           ┆           ┆          ┆ 3         │
│            ┆          ┆           ┆ 07:14:52  ┆   ┆           ┆           ┆          ┆ 00:30:55  │
│ …          ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ APF_C00758 ┆ apfel    ┆ user758@t ┆ 2026-02-0 ┆ … ┆ Edinburgh ┆ EH1       ┆ null     ┆ 2026-10-1 │
│            ┆          ┆ est.com   ┆ 9         ┆   ┆           ┆           ┆          ┆ 3         │
│            ┆          ┆           ┆ 12:29:03  ┆   ┆           ┆           ┆          ┆ 00:30:55  │
│ APF_C00759 ┆ apfel    ┆ user759@e ┆ 2026-02-1 ┆ … ┆ London    ┆ SW1A      ┆ null     ┆ 2026-10-1 │
│            ┆          ┆ mail.com  ┆ 2         ┆   ┆           ┆           ┆          ┆ 3         │
│            ┆          ┆           ┆ 15:56:44  ┆   ┆           ┆           ┆          ┆ 00:30:55  │
│ APF_C00760 ┆ apfel    ┆ user760@t ┆ 2026-02-0 ┆ … ┆ Munich    ┆ 80331     ┆ null     ┆ 2026-10-1 │
│            ┆          ┆ est.com   ┆ 1         ┆   ┆           ┆           ┆          ┆ 3         │
│            ┆          ┆           ┆ 18:30:41  ┆   ┆           ┆           ┆          ┆ 00:30:55  │
│ APF_C00761 ┆ apfel    ┆ user761@e ┆ 2026-02-1 ┆ … ┆ Frankfurt ┆ 60311     ┆ null     ┆ 2026-10-1 │
│            ┆          ┆ mail.com  ┆ 1         ┆   ┆           ┆           ┆          ┆ 3         │
│            ┆          ┆           ┆ 12:49:51  ┆   ┆           ┆           ┆          ┆ 00:30:55  │
│ APF_C00762 ┆ apfel    ┆ user762@e ┆ 2026-02-0 ┆ … ┆ Edinburgh ┆ EH1       ┆ null     ┆ 2026-10-1 │
│            ┆          ┆ mail.com  ┆ 8         ┆   ┆           ┆           ┆          ┆ 3         │
│            ┆          ┆           ┆ 08:43:49  ┆   ┆           ┆           ┆          ┆ 00:30:55  │
└────────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [6]:
client.command("DROP TABLE IF EXISTS fact_subscription_events")
client.command("DROP TABLE IF EXISTS dim_customer")